################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Â© 2025 Cool Track. All rights reserved."

