############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Features"
url = "features/"
weight = 2

[[main]]
weight = 3
name = "Industries"
hasChildren = true

  [[main]]
  parent = "Industries"
  name = "Healthcare"
  url = "industries/healthcare/"
  weight = 1

  [[main]]
  parent = "Industries"
  name = "Food Service"
  url = "industries/food-service/"
  weight = 2

  [[main]]
  parent = "Industries"
  name = "Industrial"
  url = "industries/industrial/"
  weight = 3

[[main]]
name = "Pricing"
url = "pricing/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6




# footer menu
[[footer]]
name = "Features"
url = "features/"
weight = 1

[[footer]]
name = "Pricing"
url = "pricing/"
weight = 2

[[footer]]
name = "Healthcare"
url = "industries/healthcare/"
weight = 3

[[footer]]
name = "Food Service"
url = "industries/food-service/"
weight = 4

[[footer]]
name = "Blog"
url = "blog/"
weight = 5

[[footer]]
name = "Contact"
url = "contact/"
weight = 6

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 7
