############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/line-awesome/1.3.0/css/line-awesome.min.css"

[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"

[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/aos/aos.js"

[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.min.js"

[[params.plugins.js]]
link = "plugins/rellax/rellax.min.js"

[[params.plugins.js]]
link = "plugins/cookie/cookie.js"

[[params.plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.min.js"

[[params.plugins.js]]
link = "plugins/glightbox.js"
